// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtSZoiZzA5oXn47v3LGZVm9qOT-EWVQhM',
    appId: '1:270726506268:web:770b55187c490f90423cd9',
    messagingSenderId: '270726506268',
    projectId: 'flutter-lab-project-1d4e9',
    authDomain: 'flutter-lab-project-1d4e9.firebaseapp.com',
    storageBucket: 'flutter-lab-project-1d4e9.firebasestorage.app',
    measurementId: 'G-C22RZ91DF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GeZ2QOUOekLW6kyAEe58768mMsTktj4',
    appId: '1:270726506268:android:0e63bcba4fcd5969423cd9',
    messagingSenderId: '270726506268',
    projectId: 'flutter-lab-project-1d4e9',
    storageBucket: 'flutter-lab-project-1d4e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ktNYgqDPHj6_RjXe3DZOAi7pCVjDsFY',
    appId: '1:270726506268:ios:9b513cee76f98cda423cd9',
    messagingSenderId: '270726506268',
    projectId: 'flutter-lab-project-1d4e9',
    storageBucket: 'flutter-lab-project-1d4e9.firebasestorage.app',
    iosBundleId: 'com.example.labProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ktNYgqDPHj6_RjXe3DZOAi7pCVjDsFY',
    appId: '1:270726506268:ios:9b513cee76f98cda423cd9',
    messagingSenderId: '270726506268',
    projectId: 'flutter-lab-project-1d4e9',
    storageBucket: 'flutter-lab-project-1d4e9.firebasestorage.app',
    iosBundleId: 'com.example.labProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtSZoiZzA5oXn47v3LGZVm9qOT-EWVQhM',
    appId: '1:270726506268:web:4f3d3ece24aa40a1423cd9',
    messagingSenderId: '270726506268',
    projectId: 'flutter-lab-project-1d4e9',
    authDomain: 'flutter-lab-project-1d4e9.firebaseapp.com',
    storageBucket: 'flutter-lab-project-1d4e9.firebasestorage.app',
    measurementId: 'G-7RRLQ2CH1Z',
  );
}
